/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRocketModal: typeof import('./src/components/AddRocketModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RocketCard: typeof import('./src/components/RocketCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusState: typeof import('./src/components/StatusState.vue')['default']
  }
}
